### ISSUE TITLE
menus / conversation choices?

### ISSUE THREAD

**Issue by dcsan** [dcsan/storydata#11]
what is going to be the grammar to prompt users to talk to characters?

eg in the start of the game we have:

![image](https://user-images.githubusercontent.com/514002/98506891-4efe2900-2211-11eb-89c9-d199d06f66b4.png)

this is left over from slack menus a bit and needs a lot of work to clean up

should we make the player type a response? since there isn't really a way to pick easily
we could use numbered menu

----

Your mind jumps to the upcoming weekend.

1️⃣    Is Friday payday?
2️⃣    No questions

----

and accept 1 or 2 as well as the text of the answers.
at start of the game / tutorial we could also add a prompt:

> _type 1 or 2 to choose..._

**Comment by dcsan** [comment]
Later in the game we don't need to give so many clues to the user, eg they can try giving different things to NPCs, or asking other questions based on clues we've given them.

**Comment by dcsan** [comment]
@intellikat more  info here on menus

**Comment by dcsan** [comment]
this one is pretty clunky, also near start of the game

![image](https://user-images.githubusercontent.com/514002/98507700-f62f9000-2212-11eb-9c2b-814ffed90ee9.png)

**Comment by dcsan** [comment]
this one works well i think:

![image](https://user-images.githubusercontent.com/514002/98507763-18c1a900-2213-11eb-97cb-a48c2a0a5e1c.png)

**Comment by dcsan** [comment]
I was also thinking to make the task checklist a progress gauge
![image](https://user-images.githubusercontent.com/514002/98507807-3262f080-2213-11eb-8d1d-7de90b711170.png)

task ■□□□□□
task ■■□□□□

**Comment by dcsan** [comment]
I also think these indicators are OK when there's only one choice. but they break down when there are multiple choices

![image](https://user-images.githubusercontent.com/514002/98508003-8d94e300-2213-11eb-846e-3bf957cff1bb.png)

**Comment by dcsan** [comment]
sit down :chair: 
skip the prologue :fast_forward:
![image](https://user-images.githubusercontent.com/514002/98509035-62ab8e80-2215-11eb-9553-c4eff61515ce.png)

:chair:  sit down 
:fast_forward: skip the prologue 
![image](https://user-images.githubusercontent.com/514002/98509035-62ab8e80-2215-11eb-9553-c4eff61515ce.png)

**Comment by dcsan** [comment]
we could get rid of the `sit|skip` if i mess around with this a lot.
but its still going to look ugly with duplicated icons

----

🪑 sit down
⏩ skip the prologue
🪑 1 ⏩  2

----

**Comment by dcsan** [comment]
sit down 🪑 
 skip the prologue ⏩
🪑 1 ⏩ 2

**Comment by dcsan** [comment]
spent time trying different embed formats... i think plain text actually looks better just with footer emoji

![image](https://user-images.githubusercontent.com/514002/98511945-5f66d180-221a-11eb-9944-f9f885744cd0.png)

![image](https://user-images.githubusercontent.com/514002/98511963-642b8580-221a-11eb-8462-cae4f3778eef.png)

**Comment by intellikat** [comment]
These seem fine to use throughout, rather than constantly changing specific
icons.

:one: Is Friday payday?

2️⃣ : No questions.

**Comment by dcsan** [comment]
this format is a bit ugly to type but will work.

![image](https://user-images.githubusercontent.com/514002/98515202-8ecc0d00-221f-11eb-8c37-9831733b9602.png)

![image](https://user-images.githubusercontent.com/514002/98515302-b7ec9d80-221f-11eb-9863-e22d243a0d4f.png)

**Comment by dcsan** [comment]
adding extra space anywhere it's easy to get messed up.

![image](https://user-images.githubusercontent.com/514002/98515335-c5a22300-221f-11eb-8727-d5b679244431.png)

![image](https://user-images.githubusercontent.com/514002/98515357-cfc42180-221f-11eb-9e93-3d1a3558cbfc.png)

also one small detail is the damn emoji are rendered differently. discord use their own emoji for icon attachments.

**Comment by intellikat** [comment]
Looks good with the shadowed drop-box around to separate out.

**Comment by intellikat** [comment]
Do you prefer the icon before or after the sentence?

**Comment by dcsan** [comment]
> Looks good with the shadowed drop-box around to separate out.

yeah, but that also means all that text is "code" 

some hacks on colorizing
https://www.writebots.com/discord-text-formatting/

**Comment by dcsan** [comment]
OK here are other options

![image](https://user-images.githubusercontent.com/514002/98517989-9beafb00-2223-11eb-9760-17b64e726103.png)

**Comment by dcsan** [comment]
![image](https://user-images.githubusercontent.com/514002/98518194-ec625880-2223-11eb-912d-7468287f0955.png)

```
      - match: m3
        then:
          reply: "```ini\n
1 [Sit down]\n
2 [Skip the prologue]
          ```"
          emoji:
            - 1️⃣
            - 2️⃣
```

**Comment by dcsan** [comment]
![image](https://user-images.githubusercontent.com/514002/98518296-0c921780-2224-11eb-9960-bdb80c823dca.png)

```
      - match: m4
        then:
          reply: "```ini\n
- [Sit down]\n
- [Skip the prologue]
          ```"
          emoji:
            - 1️⃣
            - 2️⃣

```

**Comment by dcsan** [comment]
![image](https://user-images.githubusercontent.com/514002/98519059-19fbd180-2225-11eb-9547-f635fc7df90b.png)

numbers only are confusing cos of the "polling" numbers next to them

**Comment by intellikat** [comment]
If we use the structure of indents for dialogue, I would say drop single or
double quotes completely. The indent replaces them as its own conceit.

**Comment by dcsan** [comment]
> drop double quotes completely. The indent replaces them as its own conceit.

yeah thats a lot easier for formatting too.

**Comment by dcsan** [comment]
![image](https://user-images.githubusercontent.com/514002/98523796-2e42cd00-222b-11eb-8af1-076d496efb1c.png)

![image](https://user-images.githubusercontent.com/514002/98523810-33a01780-222b-11eb-8d07-c2183dffd4bc.png)

removing initial spaces in lines seems really picky for this color formatting
or we get this
![image](https://user-images.githubusercontent.com/514002/98523854-44e92400-222b-11eb-852f-3881d8de2436.png)
