### ISSUE TITLE
MVP fixes

### ISSUE THREAD

**Issue by dcsan** [dcsan/storydata#13]
Here are a few things I noticed on a play-through. I could probably update the image locations myself, but didn't want to monkey around too much. We can do another run when we incorporate all these and the updates on my branches. I think we will basically have it just about all fixed then.

- [x] The command "look window" doesn't register. There is a closeup image to go with this command: bh-ch1-window.jpg
look window.png

- [x] The textual descriptions, icons, and images of lights are not in sync. At the start of the game, 0/4 lights are on. With each task completed, one should come one until all four are completed. 4 lights are not directly related to 6 tasks-- do you think this is confusing? (I don't necessarily think so)
light description.png

- [x] MJ external window is old duotone. Personally, I think this extra step is unnecessary. Maybe we can use external windows, flips, etc. later, but I think for now the command "get poster" or even "read poster" is sufficient to get the textual description on the back. Maybe even a description of "On closer inspection, you notice the poster has been peeled back before. You turn it over to find the following scrawled on the back:" to help transition.
mj flip.png

- [x] command "look wall" gets the duotone image rather than: bh-ch1-3-posters.jpg. 
- [x] Also, "look photo" or "look pic" goes to the images of MJ poster, rather than the high school photograph: bh-ch1-hs-photo.jpg
wall + photo.png

A few more inputs recognized may be helpful here:
- [x] get handle.png

- [x] Once the handle is removed (from the closed wardrobe), a matching image isn't called up.I'll draw and send this separately.
no handle look.png

- [ ] It's possible to trigger an image of the dark room before it's actually happened here.
look room.png

- [x] The old duotone image is used here instead of: bh-ch1-4-lights.jpg
4 duotone.png

- [x] The image for the door has two variations dependent on the state: closed combo lock panel and open lock panel. Currently, it just calls up the first. The second is: bh-ch1-door-with-lock.jpg
panel.png

- [x] It's hard to tell, but the first lock image is actually the old duotone one. The updated one is: bh-ch1-000-lock.jpg
Screen Shot 2020-11-10 at 12.04.28 PM.png

duotone lock.png

**Comment by dcsan** [comment]
![look window](https://user-images.githubusercontent.com/514002/98628009-66e5b380-22ca-11eb-8f56-950b9f2dad5e.png)
![light description](https://user-images.githubusercontent.com/514002/98628017-6816e080-22ca-11eb-9f37-a36a269a5c6b.png)
![mj flip](https://user-images.githubusercontent.com/514002/98628021-69480d80-22ca-11eb-997e-b2f57aa3da59.png)
![wall + photo](https://user-images.githubusercontent.com/514002/98628023-6a793a80-22ca-11eb-982a-861dd6a72354.png)
![get handle](https://user-images.githubusercontent.com/514002/98628025-6b11d100-22ca-11eb-929c-91ad4afb58ce.png)
![no handle look](https://user-images.githubusercontent.com/514002/98628026-6b11d100-22ca-11eb-83ab-f30289540655.png)
![look room](https://user-images.githubusercontent.com/514002/98628027-6baa6780-22ca-11eb-9444-97a7b764e030.png)
![4 duotone](https://user-images.githubusercontent.com/514002/98628029-6baa6780-22ca-11eb-943d-fe69e59782f7.png)
![panel](https://user-images.githubusercontent.com/514002/98628030-6baa6780-22ca-11eb-8275-35d5d31dbdd3.png)
![Screen Shot 2020-11-10 at 12 04 28 PM](https://user-images.githubusercontent.com/514002/98628031-6c42fe00-22ca-11eb-824e-7570168250a0.png)
![duotone lock](https://user-images.githubusercontent.com/514002/98628033-6c42fe00-22ca-11eb-9362-aed66eee8495.png)

**Comment by dcsan** [comment]
![image](https://user-images.githubusercontent.com/514002/98669410-315ebb80-2306-11eb-876c-80158d8c8b8f.png)

fixed window - file name bug

**Comment by dcsan** [comment]
## lights

right now 
- task1 = 1 lights
- task2 = 2 lights etc.

But it may get out of sync. it's a bit complicated/messy to track really (one thing i want to clean up with a proper hints/task system). did you notice where it goes out of sync?

or should it be 
- task1 = 0 lights
- task2 = 1 lights

maybe thats why i'm confused

![image](https://user-images.githubusercontent.com/514002/98669609-7256d000-2306-11eb-9bd6-28b77d87c4bc.png)

**Comment by dcsan** [comment]
> MJ external window is old duotone. Personally, I think this extra step is unnecessary. Maybe we can use external windows, flips, etc. later, but I think for now the command "get poster" or even "read poster" is sufficient to get the textual description on the back. Maybe even a description of "On closer inspection, you notice the poster has been peeled back before. You turn it over to find the following scrawled on the back:" to help transition.

agreed, but i want to leave this in here as a placeholder feature, when discussing new ideas. the abilty later to have integrated interactive webgames is a big feature. I'll get around to fixing it. if i do investor and other demos, i like to show this part... and it's kind of cool to some people. does need work though.

**Comment by dcsan** [comment]
>  It's possible to trigger an image of the dark room before it's actually happened here.

i think this is related to lights and tasks ordering, lets clarify https://github.com/dcsan/storydata/issues/13#issuecomment-724649015 first

**Comment by dcsan** [comment]
![image](https://user-images.githubusercontent.com/514002/98676335-535d3b80-2310-11eb-86e0-6a5cde668808.png)

**Comment by dcsan** [comment]
change door state

```
      # task #4 - color puzzle
      - match: task5
        then:
          reply: "`[Task 5/6]` A panel slides open on the door revealing a combination lock."
          emoji: [🌟]
          setProps:
            - panel.state = locked
            - lock.state = locked
            - door.state = panel
            - room.state = task5
            - tasklist.state = task5
```

![image](https://user-images.githubusercontent.com/514002/98676745-d8485500-2310-11eb-9f3b-fe8233b28e0d.png)

**Comment by dcsan** [comment]
It's hard to tell, but the first lock image is actually the old duotone one. The updated one is: bh-ch1-000-lock.jpg

**Comment by dcsan** [comment]
>  It's hard to tell, but the first lock image is actually the old duotone one. The updated one is: bh-ch1-000-lock.jpg

also i can just detect the four numbers so removed the whole "ENTER COMBO" text

![image](https://user-images.githubusercontent.com/514002/98677119-6ae8f400-2311-11eb-9ca2-748486ac4503.png)

**Comment by dcsan** [comment]
OK so these are mostly done

i've noticed some other stuff will add issues

**Comment by intellikat** [comment]
Command "get shoes" can result in getting the sandals/shoes without at least a check of the bed "look bed" or "look under bed". Might be good to require the check just as "get soap" has.

![Screen Shot 2020-11-10 at 10 46 42 PM](https://user-images.githubusercontent.com/7255631/98692239-db435400-23a9-11eb-9435-4e3fa5e32bad.png)

**Comment by intellikat** [comment]
command "get robe" can obtain the robe without actually opening the wardrobe.

![Screen Shot 2020-11-10 at 10 47 51 PM](https://user-images.githubusercontent.com/7255631/98692407-0d54b600-23aa-11eb-9e1b-c4b82887153e.png)

**Comment by dcsan** [comment]
i think ppl will only do get shoes without seeing them if they've played before?
but could add that logic in.

ugh i thought the WR thing was working before.

i wonder how much i should spend on all these script details vs. larger features like hint system. I've just spent so many days and days tweaking scripts stuff.

**Comment by dcsan** [comment]
all done except

>  It's possible to trigger an image of the dark room before it's actually happened here.

#40

**Comment by intellikat** [comment]
Yeah it still happens.
