### ISSUE TITLE
spacing

### ISSUE THREAD

**Issue by dcsan** [dcsan/storydata#16]
this seems to have too much spacing now - did you mean that?

![image](https://user-images.githubusercontent.com/514002/98677301-adaacc00-2311-11eb-8cbe-c9d9c836eff7.png)

![image](https://user-images.githubusercontent.com/514002/98677385-cd41f480-2311-11eb-9622-c1a24d0c04e9.png)

also generally i use the format 

```
\n
\ntext
```

rather than empty lines and then `\n\n` so the display maps closer to the markup

**Comment by dcsan** [comment]
before

```md

    actions:
      - match: ask|.*|👩🏼‍⚕️
        then:
          reply: "
            \nThe doctor appears to ignore you, motioning to the guards instead.

            \n\n> _Take this one to the tower._

            \n\n> Yes, Doctor Abbot._

            \n\nThe guards advance on you.

            \n\n> _Indeed... you've certainly won. And now it's time to have a closer look into that winning brain of yours._

            \n\nThe guards grab hold of you.
          "
          goto: epilogue2

```

**Comment by dcsan** [comment]
after

```

    actions:
      - match: ask|.*|👩🏼‍⚕️
        then:
          reply: "
            \nThe doctor appears to ignore you, motioning to the guards instead.
            \n
            \n> _Take this one to the tower._
            \n> Yes, Doctor Abbot._
            \n
            \nThe guards advance on you.
            \n
            \n> _Indeed... you've certainly won. And now it's time to have a closer look into that winning brain of yours._
            \n
            \nThe guards grab hold of you.
          "
          goto: epilogue2
```


![image](https://user-images.githubusercontent.com/514002/98677615-1abe6180-2312-11eb-9bc9-20bff31637cc.png)

**Comment by dcsan** [comment]
tweaked. there are two different quoted NPCs here... ?

![image](https://user-images.githubusercontent.com/514002/98677743-4a6d6980-2312-11eb-8a72-431f415464e1.png)

**Comment by dcsan** [comment]
![image](https://user-images.githubusercontent.com/514002/98677813-71c43680-2312-11eb-90cc-c3f0983f46a8.png)

goddamit ok.

**Comment by intellikat** [comment]
I meant a space gap between although it looks a bit big. A half-space would be great....
