### ISSUE TITLE
ending image?

### ISSUE THREAD

**Issue by dcsan** [dcsan/storydata#17]
wonder if there's a better image to use at the end? it looks a bit less cool now compared to the other color stuff

![image](https://user-images.githubusercontent.com/514002/98677961-a932e300-2312-11eb-9a5b-d2dc92939886.png)

**Comment by intellikat** [comment]
Yeah working on it. You can get rid of the duotone duo goons before this one. If we need an image of them advancing I can do that, but it may be fine with just the parting shot of the asylum (with a guard closing the gate I'm imagining)

**Comment by dcsan** [comment]
replaced image

are there still goons? i removed in other story 
epilogue2

**Comment by intellikat** [comment]
There is no image for the two guards approaching. Just the foot of the stairs image and the final of the gate closing.

**Comment by intellikat** [comment]
It's possible I could do a layered image of our hero, with guard arms on right and left the reach in and grab him in an animation.
