### ISSUE TITLE
ending call to action

### ISSUE THREAD

**Issue by dcsan** [dcsan/storydata#19]
i want to add some stuff here like

- invite your friends to play! (invite link)
- want to add this game to your own server? find our more here!

![image](https://user-images.githubusercontent.com/514002/98678022-c7004800-2312-11eb-8856-83fd1ca654d6.png)

also i do wanna redo that survey using typeform, it looks cooler.

or maybe we could even ask some questions directly inside the chat? but hten i need to log them
maybe there's a discord survey bot

**Comment by dcsan** [comment]
a bit better ...

![image](https://user-images.githubusercontent.com/514002/99186408-e9c0a100-2704-11eb-99bc-c8f2197cea05.png)

**Comment by intellikat** [comment]
Well, the image should be at the end. They aren't dragging you out of the
asylum into the night. You're going deeper inside. That parting shot is
outside-- basically like a nighttime lockdown so you are really trapped in
this huge asylum now. If an earlier image is necessary, I made the image of
the guards grabbing from the sides. Let's use that.

**Comment by intellikat** [comment]
![grab-vignette](https://user-images.githubusercontent.com/7255631/99187756-5bdfc700-2793-11eb-82a0-e493106d3815.jpg)

**Comment by intellikat** [comment]
Put the external gate just before the thank you for playing.

**Comment by dcsan** [comment]
![image](https://user-images.githubusercontent.com/514002/99191160-b63f4000-271f-11eb-84b0-dee82137ff93.png)

moved to next block.
