### ISSUE TITLE
fix MJ image in web popup

### ISSUE THREAD

**Issue by dcsan** [dcsan/storydata#20]
also change the scaling to fit inside window

**Comment by dcsan** [comment]
![Uploading image.png…]()

**Comment by dcsan** [comment]
![image](https://user-images.githubusercontent.com/514002/99177287-5a919a00-26c0-11eb-9cea-7b153e0067b6.png)

**Comment by dcsan** [comment]
still need to fix CSS on back to match front
complex due to supporting any aspect ratio 

![image](https://user-images.githubusercontent.com/514002/99177597-72691e00-26c0-11eb-9afa-c647c7b2cbc9.png)

**Comment by intellikat** [comment]
Do you need the matching background for this as a separate image rather
than a fake grey brick wall?

**Comment by dcsan** [comment]
yeah a bg would be good. a tile pattern would be best - this expands to fill the screen as it can be any shape/size.

tall / wide etc.

**Comment by intellikat** [comment]
It should be consistent with the actual wall image though.

**Comment by intellikat** [comment]
The wall in the room isn't a brick wall.

**Comment by dcsan** [comment]
yeah just the color then?

**Comment by intellikat** [comment]
No I'll make it match with the texture of the illustration. Is this a square?

**Comment by dcsan** [comment]
actually i did it with code

but i can use an image. anything that tiles should be ok

```
.brick {
  width: 100vw;
  height: 100vh;
  background-color: #DFDBE5;
  background-image: url("data:image/svg+xml,%3Csvg width='42' height='44' viewBox='0 0 42 44' xmlns='http://www.w3.org/2000/svg'%3E%3Cg id='Page-1' fill='none' fill-rule='evenodd'%3E%3Cg id='brick-wall' fill='%239C92AC' fill-opacity='0.4'%3E%3Cpath d='M0 0h42v44H0V0zm1 1h40v20H1V1zM0 23h20v20H0V23zm22 0h20v20H22V23z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E");
  z-index: 1;
}
```

**Comment by intellikat** [comment]
Oh, needs to tile? Can't be a single image?

**Comment by dcsan** [comment]
no... that would be huge. i mean, i guess it could be... but if its just a small thing its a waste to have a full screen
if its a small JPG i could scale it to fill

**Comment by intellikat** [comment]
This is the actual.

![mj-background-01](https://user-images.githubusercontent.com/7255631/99187404-6600c600-2791-11eb-9b02-8bdfed4d622b.png)

**Comment by intellikat** [comment]
Simplified.
![mj-background-02](https://user-images.githubusercontent.com/7255631/99187498-f0492a00-2791-11eb-9a71-84a6235e5b6d.png)

**Comment by intellikat** [comment]
Or tile the general color.
![mj-wall-tile](https://user-images.githubusercontent.com/7255631/99187560-4322e180-2792-11eb-89a5-5c78d1b730f9.png)

**Comment by dcsan** [comment]
think it should be a color or pattern or you'll notice it floating around maybe

**Comment by dcsan** [comment]
rgb 184, 174, 130

**Comment by dcsan** [comment]
#B8AE80

**Comment by dcsan** [comment]
![image](https://user-images.githubusercontent.com/514002/99190620-58f5bf80-271c-11eb-8d06-8658a05eba59.png)

i can mix texture and the color

**Comment by dcsan** [comment]
i guess i could do a gradient color from code... 
agh i'll spend time on other stuff

![image](https://user-images.githubusercontent.com/514002/99190635-7591f780-271c-11eb-8345-aa2348c4e22c.png)

**Comment by dcsan** [comment]
I like the transparent masking tape on the davinci.
paper textures are nice.


![Screen Shot 2020-11-11 at 08 02 55](https://user-images.githubusercontent.com/514002/99190654-94908980-271c-11eb-82e8-ee7e2e43eb37.png)

**Comment by intellikat** [comment]
Flat yellow-tan is fine for now. Can fix it later. Don’t put a background
that doesn’t match the actual game image... it looks tacky and is
confusing.
