### ISSUE TITLE
start sequence

### ISSUE THREAD

**Issue by dcsan** [dcsan/storydata#21]
- use/create an animated GIF
- use an embed?
- remove the first step - just reset to the start frame

![image](https://user-images.githubusercontent.com/514002/98678734-dd5ad380-2313-11eb-9178-ec4398104c1d.png)

**Comment by dcsan** [comment]
add more call to action to "invite your friends!" its more fun to play as a group

**Comment by intellikat** [comment]
How about just a pulsing torch light on top of this image as the animation? or it goes from blackout to torch light on, and then the torchlight flickers out? Classic, cool, simple.

What would be really cool is:

1. Black
2. Torch light flickers on (basically just oscillate between a black screen and the image at the right speed)
3. Add a layer of a dark silhouette (like a giant rat) that moves out of frame at the bottom right as the torch light is flickering on.
