### ISSUE TITLE
tutorial room

### ISSUE THREAD

**Issue by dcsan** [dcsan/storydata#25]
currently I have a basic tutorial in the cell room
but it would be better to have either a separate room, or mini-sequence we can reuse for this.
ie just talking to a host NPC, "in character" of the game
but ideally that could be put before each episode. (so players joining on EP2 can also get this)

just to get them to use basic commands like Look, Get, Use, Examine etc.

**Comment by dcsan** [comment]
@intellikat ideas for what we could use for this?

**Comment by intellikat** [comment]
Most elegant solution is to do it in the cell room as you have. There are potentially other commands or actions that could be designed into this tutorial but I think you've given enough to get them going. Another option is to design this into the prologue, in the Chief's office. 

"look at this, Dale." The Chief points to a black and white photo.

> look photo

But unless ppl are currently really stumbling fuckily over everything in the game, I feel we can wait on this.

**Comment by dcsan** [comment]
this is OK for now unless we have multiple stories.

**Comment by dcsan** [comment]
some people are stumbling tho, its pretty odd to see. others know exactly what to do...

**Comment by dcsan** [comment]
also if we invite people in who aren't heavy discord users, the whole click on emoji thing is very weird to them.
