### ISSUE TITLE
GIF animation

### ISSUE THREAD

**Issue by dcsan** [dcsan/storydata#27]
for dropping "ads" into other discords 👍 

animated gif with https://ten.rik.ai as the URL embedded in the image / anim in case we can't spam links

needs some quick animation clips from the gameplay itself, eg showing using discord chat and channels

**Comment by dcsan** [comment]
it took a long time to make this last time
maybe i can reuse some of the elements?

there is no "nurse" now tho, right?

any other scene that you think we could take the elements from to animate?

this isn't a good one but something short, sweet, that loops and is dramatic

![asylum-intro-pong](https://user-images.githubusercontent.com/514002/98962401-75df8800-24bb-11eb-8c55-9a018b266a5f.gif)

**Comment by intellikat** [comment]
There's no nurse, no white dude, no white girl anymore. Only blue bathrobes and sinks.

Do you want me to give you elements for a new one? Now knowing you are putting it together as animation, and knowing the purpose for it (ads), I can better design it.
