### ISSUE TITLE
landing page background

### ISSUE THREAD

**Issue by dcsan** [dcsan/storydata#36]
we need a landing page
should have the logo at the right hand side as discord puts stuff on the left

![image](https://user-images.githubusercontent.com/514002/99180247-6a69a800-26d9-11eb-9cad-e3983504117d.png)

**Comment by intellikat** [comment]
OK. Do you have the image ratio? Which logo? BPO? BOO? TEN? Alibaba?

**Comment by intellikat** [comment]
I didn't know the image ratio, but this is based roughly on a screen cap. Should be close.

![bopo-landing-page-01](https://user-images.githubusercontent.com/7255631/99186523-c7be3180-278b-11eb-8bf3-07c2b6da2df4.png)

**Comment by dcsan** [comment]
16:9 aspect ratio. 
1920x1080 


Your Invite Splash Image is going to be set up in a very similar way. The image that you’re setting up here is what appears when using an invite link in a web browser. For example, if you go to https://discord.gg/apex you see:

https://support.discord.com/hc/en-us/articles/360028716472

when we get more users we can get other stuff

**Comment by dcsan** [comment]
OK thats good

**Comment by intellikat** [comment]
Hang on

**Comment by dcsan** [comment]
depends how people have their screen setup where it all falls.

![image](https://user-images.githubusercontent.com/514002/99186806-afa4ce80-2707-11eb-9288-5a9feb18b0b1.png)

![image](https://user-images.githubusercontent.com/514002/99186812-b92e3680-2707-11eb-9402-da3a743dfcc4.png)

![image](https://user-images.githubusercontent.com/514002/99186814-bdf2ea80-2707-11eb-9487-32577a44e9df.png)

**Comment by dcsan** [comment]
https://discord.com/invite/DAQju22QYU

try it here ^

**Comment by intellikat** [comment]
The server banner ought to have the server title up top. If that is TEN and not BoPO then it will be a bit confusing. If it's TEN it should be TEN, if BoPO then BoPO really. 

Guidelines say not to add text or logos to the image itself. Here are two versions.

![bopo-landing-page-01](https://user-images.githubusercontent.com/7255631/99186835-fd641a00-278d-11eb-82d8-15df046c2b69.png)
![bopo-landing-page=02](https://user-images.githubusercontent.com/7255631/99186836-fe954700-278d-11eb-9c2e-4d99b58645e4.png)

**Comment by dcsan** [comment]
we dont have a server banner yet

![image](https://user-images.githubusercontent.com/514002/99186876-17f3b000-2708-11eb-9a45-ac2601b95b6b.png)

level 2 = 15 boosts ~= $50/month

![image](https://user-images.githubusercontent.com/514002/99186887-32c62480-2708-11eb-9ac0-a402f892b9ea.png)

ideally if people like our game they'll boost the server...

![image](https://user-images.githubusercontent.com/514002/99186885-25a93580-2708-11eb-9e66-aa1befd306a7.png)

**Comment by dcsan** [comment]
i think the logos a good add

we could do a verison of it tho laid out horizontal (side by side text + badge) at bottom of the screen?
then its almost never covered

**Comment by dcsan** [comment]
for reference put this in
the image is always adjusted from the bottom up
and crops off from the top.. weird.

![image](https://user-images.githubusercontent.com/514002/99186957-b41db700-2708-11eb-8e43-7624752d730b.png)

**Comment by intellikat** [comment]
Good call. You choose.

![bopo-landing-page-03](https://user-images.githubusercontent.com/7255631/99188204-b24e0500-2795-11eb-86c7-636241fc45f7.png)
![bopo-landing-page-04](https://user-images.githubusercontent.com/7255631/99188212-b8dc7c80-2795-11eb-955a-4d2febb287d2.png)

**Comment by intellikat** [comment]
(the last one is the best)

**Comment by dcsan** [comment]
done!
