### ISSUE TITLE
change start frame on GIF

### ISSUE THREAD

**Issue by dcsan** [dcsan/storydata#37]
![image](https://user-images.githubusercontent.com/514002/99183065-17e6b680-26ee-11eb-8def-6eb73a9c2ff7.png)

the banner gif has a black resting frame
when you unfocus discord it stops here.
i think cos this is the first frame? or last?

can you change it so there's a better image to stop on?

**Comment by intellikat** [comment]
You're right-- it's due to it being the first frame. I can swap so that BPO
is the first frame.

Are we going with Bureau of Profound Oddities or Bureau of Oddities? I like
the feel of the longer name and think that it will be memorable if it make
it so with a quality game.

**Comment by intellikat** [comment]
![bpo-creature-promo](https://user-images.githubusercontent.com/7255631/99185375-69da1b80-2784-11eb-900e-fba16a9ff5bc.gif)

**Comment by dcsan** [comment]
I prefer BoPo as an abbreviation to BPO
I have a bit of love/hate with the full name, its cool and weird when i read it but it doesn't stick in my head.
lets go with it, i'll have to ask some other folks too
