### ISSUE TITLE
animated server icon

### ISSUE THREAD

**Issue by dcsan** [dcsan/storydata#39]
![image](https://user-images.githubusercontent.com/514002/99185561-854f1300-26ff-11eb-9002-613f5a4a0685.png)

I changed server icon to this now
if we had a two frame gif it would be more memorable maybe between that and BoPo ?
or a zoom into the owl...

**Comment by intellikat** [comment]
How to do that? A square framed GIF with circular images that will be cropped down when you select it for the icon?

**Comment by intellikat** [comment]
Does it need to be two frames only?

**Comment by dcsan** [comment]
no it can be as many frames 

The max file size I've heard for the server icon is 8 MB.

they recommend 512x512
but i think smaller but more animation would be better.

something with lots of contrast or cool disc that rotates on the Y axis?

**Comment by intellikat** [comment]
![bopo-server-icon](https://user-images.githubusercontent.com/7255631/99190008-2b058f00-279f-11eb-952f-8ec3a4ccf54f.gif)

**Comment by dcsan** [comment]
cute!

**Comment by dcsan** [comment]
hmm doesn't seem to be showing up

![image](https://user-images.githubusercontent.com/514002/99190688-f224d600-271c-11eb-8691-518df4c10279.png)

**Comment by dcsan** [comment]
I was also thinking we can do 

Bo
PO

for a logo later. like the NY 

LO
VE

would fit in circle a bit better.

**Comment by dcsan** [comment]
is there anything odd about the GIF? it works for me everywhere else. hmm.

![image](https://user-images.githubusercontent.com/514002/99190747-3ca65280-271d-11eb-9a84-32a02997c3dc.png)

works in settings screen but not in discord itself... hmm.

**Comment by dcsan** [comment]
![image](https://user-images.githubusercontent.com/514002/99190944-70ce4300-271e-11eb-9c30-9172ef4902f6.png)

btw it's antialiased to white which looks a bit janky on dark mode

![image](https://user-images.githubusercontent.com/514002/99190963-804d8c00-271e-11eb-8cc4-66d22c948e5b.png)

**Comment by intellikat** [comment]
I can fix the antialiasing. Does discord limit the file size and then just
make it static if exceeded? Can make bopo love

**Comment by intellikat** [comment]
Does asylum-dev need a new icon? What boys need icons?

**Comment by intellikat** [comment]
Apparently I can't fix the AA when making GIFs in PS. But I added a matching blue background, which should just disaappear when cropped as a circular icon. If the GIF doesn't play in Discord it must be related to the file size.

**Comment by intellikat** [comment]
![bopo-server-icon-FINAL](https://user-images.githubusercontent.com/7255631/99200658-996b4100-27e1-11eb-91aa-20be62476449.gif)

**Comment by dcsan** [comment]
> Does asylum-dev need a new icon? What boys need icons?
nah, thats just for development /testing

full bleed background looks good. it will crop itself

**Comment by dcsan** [comment]
it works now. as a point, it would be good to have zero pause on any frame
currently when you rollover the loog you have to wait a few moments for anything to happen
some other server logos animate instantly, so even a mouse over attracts the eye.

![logoanim](https://user-images.githubusercontent.com/514002/99256640-8bf68c80-27ca-11eb-9b08-e1f6b66155ca.gif)

**Comment by dcsan** [comment]
https://www.reactiflux.com/

one seems to work a lot better.
very few server logos are animated tho, so this is a differentiator

**Comment by intellikat** [comment]
use this

![bopo-server-icon-REVISED](https://user-images.githubusercontent.com/7255631/99323540-6aba9c80-28ad-11eb-91ab-8224c226c32c.gif)

**Comment by dcsan** [comment]
yeah! that works much better, instant gratification on rollover...
