### ISSUE TITLE
bureau version changes

### ISSUE THREAD

**Issue by dcsan** [dcsan/storydata#5]
less aggressive 'help' icon? by some rule... ? 50% time at least?

add icon 🌟  
This icon shows you are making progress!

**Comment by dcsan** [comment]
tannoy and audio cues
try a webhook to get a different (tannoy) icon?

**Comment by dcsan** [comment]
fix voice invite

**Comment by dcsan** [comment]
cc @intellikat making some notes as i play through with people, feel free to add other stuff here you want me to fix.

**Comment by intellikat** [comment]
> less aggressive 'help' icon? by some rule... ? 50% time at least?
> 
> add icon 🌟
> This icon shows you are making progress!

Can we make bespoke icons?

**Comment by dcsan** [comment]
Yes we can make custom emoji, up to 50 for the server. Trust could be a
really good way to indicate choices

**Comment by intellikat** [comment]
What kind of icons would be helpful to customize?

I don't know what you mean by "Trust could be a
really good way to indicate choices"

**Comment by dcsan** [comment]
voice dictation - trust = this could be a really good way ...

basically we want icons to go with the choices in dialogs
eg I picked out these options

![image](https://user-images.githubusercontent.com/514002/98438941-bcd81280-20a2-11eb-9471-293e34367aed.png)
