### ISSUE TITLE
game ending

### ISSUE THREAD

**Issue by dcsan** [dcsan/storydata#9]
currently the story ends here, but i think you wanted it to use the bottom of the stairs image

is there a script for this part? I seem to have mislaid it if you sent it at some point

![image](https://user-images.githubusercontent.com/514002/98441238-e64c6a80-20b1-11eb-90df-79a26277abcb.png)

**Comment by intellikat** [comment]
All of that old script and images is to be replaced.

I wrote the new text into my branch for the epilogues.

It's shorter and the image would fit in once leaving the cell somewhere.

**Comment by intellikat** [comment]
That script is the updated one. Just remove the images and add the curving staircase one.

You had then linked to epilogue #2, which I updated in my branch.

**Comment by dcsan** [comment]
ok got it

also JFYI on formatting with quotes etc, ithink you wanted to have extra line spaces?

now its:

```
          reply: "
            > _\"Take him to the tower\"_
            \nthe doctor says, motioning to two burly guards.
            \n\"Yes, Doctor Abbot.\" They advance on you.
            \n> _\"We have a few questions to ask you.\"_
            \n he says, as the guards grab hold of you.
          "
          goto: epilogue2
```

![image](https://user-images.githubusercontent.com/514002/98502596-49034a80-2207-11eb-8e00-887e6dcda79e.png)

**Comment by dcsan** [comment]
![image](https://user-images.githubusercontent.com/514002/98503638-de9fd980-2209-11eb-908e-e12f092abb25.png)

final

**Comment by dcsan** [comment]
also added some docs here on formatting with quotes etc.

https://github.com/dcsan/storydata/blob/master/docs/yaml-editing.md

**Comment by intellikat** [comment]
I'm just looking for a consistent format throughout for the text that aids
readability. If it's messy and inconsistent, the player is likely to skip
through.

What tools do we have in order to format the descriptions? Line breaks,
indents (being used now for dialogue), anything else? If I know this, I can
find a way to write that is both terse and readable.

**Comment by intellikat** [comment]
Okay, I think you've answered my question about formatting tools.

**Comment by dcsan** [comment]
i added some notes on formatting, see the link above.

the line breaks look nice, on desktop, but does take a lot of vertical space.

we don't have that much really just very basic markdown

https://support.discord.com/hc/en-us/articles/210298617-Markdown-Text-101-Chat-Formatting-Bold-Italic-Underline-

they also have embeds but we really haven't used that too much
https://discordjs.guide/popular-topics/embeds.html
https://anidiots.guide/first-bot/using-embeds-in-messages

https://discohook.org/

i was thinking about using embeds for items you can pick up

we can also send videos, and 'text to speech'
i was thinking about using that for the tannoy system.

**Comment by intellikat** [comment]
I'm not terribly fond of using icons... all the icons and options seem to
clutter up the interface and get away from the idea of typing commands. But
if they are used, I think they need to be likewise consistent and maybe
eventually designed visually to match style of the game.

[image: Screen Shot 2020-11-09 at 2.04.38 PM.png]

In the above example, consistency would mean:

sit (icon) down
skip (icon) the intro

So that the operative word is first and linked directly to the icon.

Why is there the "poll results" below for the choices made?

**Comment by dcsan** [comment]
i don't see the image above, can you send again? 

not sure what you mean by "poll results" ?

I think in the intro having some buttons to skip through is good, it keeps the pace going.
esp originally it was a lot of screens without any choices.
but in general we could stick to a grammar of "talking to characters is always via chat" and that would open up more options for depth.

**Comment by dcsan** [comment]
I do really like the main "controls" navigation menu as it presents a few options and makes it clear what you can do:

![image](https://user-images.githubusercontent.com/514002/98506441-5cff7a00-2210-11eb-8ff3-eae16b53b2a5.png)

we don't have a tutorial, so previously in the cell I did lead them through the first two commands.
it was amazing how many people did not know how to type `look` or know how to pick stuff up

this one is OK:

![image](https://user-images.githubusercontent.com/514002/98506492-7c96a280-2210-11eb-85a9-79b38460217f.png)

this seems to have got messed up:
![image](https://user-images.githubusercontent.com/514002/98506539-99cb7100-2210-11eb-869e-923b5ee83ab5.png)

**Comment by dcsan** [comment]
I was maybe going to use an embed for some hints / help tools

**Comment by dcsan** [comment]
there also isn't a good emoji to indicate 'help' stuff 
![image](https://user-images.githubusercontent.com/514002/98506651-d5fed180-2210-11eb-8013-85fd011d0b0e.png)

![image](https://user-images.githubusercontent.com/514002/98506681-e911a180-2210-11eb-9429-bb82caf2d9df.png)

**Comment by intellikat** [comment]
![Screen Shot 2020-11-09 at 11 57 35 AM](https://user-images.githubusercontent.com/7255631/98506766-346e9300-2297-11eb-8d67-cf76becb4da8.png)

poll results = it shows how many times a player has pushed a certain button, doesn't it?

It's fine to have the option to skip or progress a screen-- I'm just saying the current interface is inelegant. Multiple icons, uses of sit and skip, a register counting how many times the button has been pressed. The original buttons that clicked through in the first duotone version were simple.

I think it's fine to teach players in the early stages how to use basic commands using the prompts you've incorporated, and maybe it's best to design that progression into the game, i.e. first "task" requires looking, second requires opening and getting, etc. It just overall feels cluttered to me with so many.

There are times you've put in the controls nav menu such that it gives away what needs to be done, such as with the MJ poster.

**Comment by intellikat** [comment]
![Screen Shot 2020-11-09 at 2 04 38 PM](https://user-images.githubusercontent.com/7255631/98507163-0473bf80-2298-11eb-9911-974d659aa0f4.png)

poll results = it shows how many times a player has pushed a certain button, doesn't it?

It's fine to have the option to skip or progress a screen-- I'm just saying the current interface is inelegant. Multiple icons, uses of sit and skip, a register counting how many times the button has been pressed. The original buttons that clicked through in the first duotone version were simple.

I think it's fine to teach players in the early stages how to use basic commands using the prompts you've incorporated, and maybe it's best to design that progression into the game, i.e. first "task" requires looking, second requires opening and getting, etc. It just overall feels cluttered to me with so many.

There are times when the controls nav menu gives away what needs to be done, such as with the MJ poster... "flip". Overall that MJ sequence feels like it's attempting to use too many mechanics and feels clunky as well. I really think it's best to focus on a clear flow through of a good story and puzzles and then incorporate mechanics as we iterate.

**Comment by dcsan** [comment]
click count = yeah we can't change that it's a discord UX thing. shows how many players have clicked. might be fun later if we do multiplayer mechanics

current UI isn't elegant, i agree. but it's the only way to do buttons currently. when their long talked about bot UX drops there will be more features, but that could be six months. 
https://blog.discord.com/the-future-of-bots-on-discord-4e6e050ab52e

what do you suggest for the menu above then?
menus and 'button choices' in general is a bigger topic, i opened this issue to discuss
https://github.com/dcsan/storydata/issues/11

**Comment by intellikat** [comment]
I think the concept behind the menu is fine, just the UI execution.

Just:

have a seat (icon)
skip the intro (icon)

where clicking the icon or the hyperlinked line itself gets you going through.

**Comment by intellikat** [comment]
Or just hyperlinked text to click still I think works as a button even without an icon.

**Comment by dcsan** [comment]
hyperlinks would be great, but discord doesn't support it.
could do that with telegram or slack... 🤦
